### ISSUE TITLE
Feature request: Blob access interface

### ISSUE THREAD

**Issue by stakemura** [creativecreatorormaybenot/microphone#10]
Great work on this plugin. 

Would you like to add `blob` access interface to `MicrophoneRecording' ?  
As the following code shows, blob is not accessible currently.

```
  /// Stops the recorder and returns an URL pointing to the recording.
  Future<String> stop() async {
    assert(_mediaRecorder != null);

    final completer = Completer<String>();

    void onStop(_) {
      assert(_audioBlobParts != null);

      final blob = Blob(_audioBlobParts); // I want to access it!
      _audioBlobParts = null;

      completer.complete(Url.createObjectUrl(blob));
    }

    _mediaRecorder.addEventListener('stop', onStop);
    _mediaRecorder.stop();
    final url = await completer.future;
    _mediaRecorder.removeEventListener('stop', onStop);

    return url;
  }
```

However, In similar to URL, I want to access blob for cooperation with FileReader or FormData.

I'm quite newbie with Dart. So I really appreciate the help.

Thanks.

**Comment by creativecreatorormaybenot** [comment]
@stakemura Thanks a lot for opening this issue 😃

You should just be able to do `Blob(url)` in your own code. Did you try that and experience any problems with it?

You will need to import `dart:html` for that.

**Comment by stakemura** [comment]
Thanks for your comment.
Unfortunately, I faced `The argument type 'String' can't be assigned to the parameter type 'List<dynamic>'.` error.
I will try to implement the original package.

Thanks.

**Comment by creativecreatorormaybenot** [comment]
@stakemura Oh I am so sorry - I sent the wrong solution.

This is the snippet you need to use (again, needs `dart:html`):

```dart
final result = await window.fetch(url);
final blob = await result.blob() as Blob;
```

**Comment by stakemura** [comment]
I appreciate your kindness.
To avoid overhead of url -> blob conversion, I will re-implement my own web audio recorder.

Thanks!

**Comment by creativecreatorormaybenot** [comment]
@stakemura I understand your concern. I also struggled with this thought. The reason I decided to keep the API minimal for a start is because I wanted to leave it open for other platform implementations as well.

I am glad to accept PRs. I will work on this plugin more soon as well :)

Either way, I am interested in your efforts.
