### ISSUE TITLE
Question: Can this be used without network connection?

### ISSUE THREAD

**Issue by RevanthRameshkumar** [creativecreatorormaybenot/microphone#11]
I'm a little confused at the URL terminology. Does this require network to access the recording (meaning, is the recording stored off device)?

**Comment by creativecreatorormaybenot** [comment]
Hi @RevanthRameshkumar, thanks for opening the issue 🙂 

The URL points to a recorded `blob`, i.e. it is a `blob:` URL.  
The blobs are created on-device, so you should be able to use the plugin without internet access.

Using [`just_audio`s `setUrl`](https://pub.dev/packages/just_audio), you should be able to play the audio even when offline.

Does this answer your question? 🙂

**Comment by RevanthRameshkumar** [comment]
Ah yes, thanks!
