### ISSUE TITLE
Get Uint8List of url recording

### ISSUE THREAD

**Issue by arefhosseini** [creativecreatorormaybenot/microphone#15]
Hey there, thanks for creating this library.
I'm recording and after stopping want to upload my recording file as `Uint8List`. 
Is there any way to get and convert data to `Uint8List`?

**Comment by creativecreatorormaybenot** [comment]
Hi @arefhosseini - thanks for asking this question 😃

Check https://blogs.ashrithgn.com/a-simple-way-to-upload-a-file-to-server-from-flutter-web-app/, which explains how to do it. The URL you got points to a blob :)

Do you think this should be added to the docs or as a feature?

**Comment by arefhosseini** [comment]
That's a good sample, seems works I think, so much appreciate.
I searched some about `blob` & find out, you can easily get the data from simple GET request by [this link](https://stackoverflow.com/a/11901662/4696843)

Here is my sample code, using `http` library:
```dart
Future<http.Response> getBlobData(String url) async {
  return http.get(
    Uri.encodeFull(url),
  );
}
//
//
getBlobData(_recorder.value.recording.url).then((response) {
  response.bodyBytes // the Uint8List data
});
```

But I think the link that you mentioned works correctly too.

**Comment by creativecreatorormaybenot** [comment]
@arefhosseini Yes, true! I think I mentioned this in another issue as well, but I did not have the reference.

Do you think that I should just add this to the docs or provide it as part of the API?

**Comment by arefhosseini** [comment]
Well according to developers requirement, most of them want to send this data to backend or sth like this.
I think it would be a great step for add another features like `recordingDuration` or multi type saving file.
For these we should fetch the data into file.
In case if you have enough time to develop these kinda features, but you can simply add this to the doc instead xD.

**Comment by creativecreatorormaybenot** [comment]
@arefhosseini The way I do it is using [`putBlob`](https://pub.dev/documentation/firebase_storage/latest/firebase_storage/Reference/putBlob.html), however, I will add the bytes getter anyway :)
