### ISSUE TITLE
what format is the bytes array of audio

### ISSUE THREAD

**Issue by expertmars** [creativecreatorormaybenot/microphone#24]
i am using nodejs backend and audio_loader module. I am passing the recorded toBytes() to backend and it makes the file of audio. I am able to play the audio with .m2a format on mac.

But, audio_loader is rejecting the audio file with reason "Source is not valid". What is the format of audio the microphone plugin is generated? is there any headers included ?

**Comment by creativecreatorormaybenot** [comment]
hi @expertmars - this plugin simply uses [the `MediaRecorder` API](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API). So anything you want to find out about the plugin of this kind of nature, you should research these APIs.

**Comment by AbdullahGaber** [comment]
@expertmars Do you know the format?

**Comment by creativecreatorormaybenot** [comment]
@AbdullahGaber the format depends on the browser used.  
For example, Firefox uses `ogg` (`.oga`) and Chrome uses `webm` (`.weba`).

This is why there is no singular answer to this question and you should instead refer to your browser's specification of the `MediaRecorder` API.

**Comment by AbdullahGaber** [comment]
@creativecreatorormaybenot so, when i send it to backend which extension should i use?
cuz both of them didn't work with me!

**Comment by masus04** [comment]
Is there any news on this? I understand this depends on the underlying APIs, but it would be very appreciated if you could share some of your insight.

As far as I understand, the data has to be sent to the backend as bytes using the `microphoneRecorder.toBytes()` method, correct?

Then how do we determine how to interpret it in the backend? Or is there a better alternative?

I assume this is a very common use case.

**Comment by masus04** [comment]
Can we reopen this issue?
