### ISSUE TITLE
Iphone exception

### ISSUE THREAD

**Issue by dannyxu2015** [creativecreatorormaybenot/microphone#29]
When use iphone simulator to run the example, it raised exception: 
PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))

Is it a permission issue? How can I fix that, and how to set permission in Android environment

**Comment by creativecreatorormaybenot** [comment]
Hi - if you check the package on Pub (https://pub.dev/packages/microphone), you will notice that it only supports **web** at this time.

**Comment by dannyxu2015** [comment]
Thanks, my carelessness~
