### ISSUE TITLE
Stream bytes? | real-time audio

### ISSUE THREAD

**Issue by AndrusGerman** [creativecreatorormaybenot/microphone#30]
Any way to get the audio in real time?
I'm creating an application that sends the audio to the server in real time, but I can't find related documentation

**Comment by creativecreatorormaybenot** [comment]
Hi! This is currently not possible using the plugin. It is implemented using the [`MediaRecorder` API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder).

You might want to check if this API supports what you are trying to achieve and then we could think about integrating it into the package.
