### ISSUE TITLE
Feature request: Download audio to a mp3 file

### ISSUE THREAD

**Issue by happyharis** [creativecreatorormaybenot/microphone#8]
Great work on this plugin. However, was wondering on how to download the audio file?

Currently it is playing from a url as such `blob:http://localhost:51895/8dacf414-0785-4e32-b395-4c99abec8b64`.

**Comment by creativecreatorormaybenot** [comment]
Thanks a lot for using the plugin!

The files are not recorded in `.mp3` and conversion is not an option client-side. I will add a download option, but you will need to convert to mp3 server-side or on your machine 🙂

**Comment by creativecreatorormaybenot** [comment]
@happyharis I actually thought about this a little more and think that this functionality should live in a separate plugin, i.e. a downloader plugin.

Closing this for now.
